const LatestData = [
    {
        id: 1,
        videoimg:'/Goalpics/brann.jpg',
        homelogo: '/clublogos/Brann.png',
        homegoal: '2',
        clubscorer: 'Brann',
        scorer: "Robert Thomas Taylor",
        awaylogo: '/clublogos/Odd.png',
        awaygoal: '1',
        videosource : "https://highlights.eliteserien.no/playlist/ax4gt1sr1jd5k",
    },
    {
        id: 2,
        videoimg:'/Goalpics/mjondalen.jpg',
        homelogo: '/clublogos/Mjondalen.png',
        homegoal: '3',
        clubscorer: 'Mjøndalen',
        scorer: "Christian Andreas Gauseth",
        awaylogo: '/clublogos/Aalesund.png',
        awaygoal: '0',
        videosource : "https://highlights.eliteserien.no/playlist/aigcdzugl37ne",
    },
    {
        id: 3,
        videoimg:'/Goalpics/bodo.jpg',
        homelogo: '/clublogos/BodoGlimt.png',
        homegoal: '3',
        clubscorer: 'Bodø/Glimt',
        scorer: "Sondre Brunstad Fet",
        awaylogo: '/clublogos/Viking.png',
        awaygoal: '0',
        videosource : "https://highlights.eliteserien.no/playlist/akozsc4p6z2e7",
    },
    {
        id: 4,
        videoimg:'/Goalpics/haugesund.jpg',
        homelogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubscorer: 'Haugesund',
        scorer: "Ibrahima Wadji",
        awaylogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        videosource : "https://highlights.eliteserien.no/playlist/abn35s4soxykd",
    },
    {
        id: 5,
        videoimg:'/Goalpics/valerenga.jpg',
        homelogo: '/clublogos/Valerenga.png',
        homegoal: '4',
        clubscorer: 'Vålerenga',
        scorer: "Osame Sahraoui",
        awaylogo: '/clublogos/Start.png',
        awaygoal: '0',
        videosource : "https://highlights.eliteserien.no/playlist/a9wwtrc2vq1kv",
    },
];

export default LatestData;