const LatestCardData = [
    {
        id: 1,
        videoimg:'/videopics/christope gul.jpg',
        hlogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubcard: 'Kristiansund',
        player: "Christope Charles Steven Rene Psyche",
        alogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/abd15527c4mb",
    },
    {
        id: 2,
        videoimg:'/videopics/bruno gul.jpg',
        hlogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubcard: 'Haugesund',
        player: "Bruno Miguel Santos Leite",
        alogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/a9u158r9ilsqf",
    },
    {
        id: 3,
        videoimg:'/videopics/kristoffer gul.jpg',
        hlogo: '/clublogos/Sandefjord.png',
        homegoal: '4',
        clubcard: 'Sandefjord Fotball',
        player: "Kristoffer Norman Hansen",
        alogo: '/clublogos/Rosenborg.png',
        awaygoal: '0',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/accjv9yzz0bv6",
    },
    {
        id: 4,
        videoimg:'/videopics/lars gul.jpg',
        hlogo: '/clublogos/Sandefjord.png',
        homegoal: '4',
        clubcard: 'Sandefjord Fotball',
        player: "Lars Grorud",
        alogo: '/clublogos/Rosenborg.png',
        awaygoal: '0',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/a4uwwlp1cqhwe",
    },
];

export default LatestCardData;