const LatestGoalData = [
    {
        id: 1,
        videoimg:'/videopics/haugesund mal.jpg',
        hlogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubscorer: 'Haugesund',
        scorer: "Ibrahima Wadji",
        alogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/as10uqa7czeof",
    },
    {
        id: 2,
        videoimg:'/videopics/haugesund mal 2.jpg',
        hlogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubscorer: 'Haugesund',
        scorer: "Ibrahima Wadji",
        alogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/ap0r2v7q25ekt",
    },
    {
        id: 3,
        videoimg:'/videopics/haugesund mal 3.jpg',
        hlogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubscorer: 'Haugesund',
        scorer: "Ibrahima Wadji",
        alogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/abn35s4soxykd",
    },
    {
        id: 4,
        videoimg:'/videopics/kristiansund mal.jpg',
        hlogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubscorer: 'Kristiansund',
        scorer: "Pemi Moumbagna Faris",
        alogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/ai2sal9urdnwf",
    },
];

export default LatestGoalData;