const MostPopularData = [
    {
        id: 1,
        videoimg:'/videopics/haugesund mal.jpg',
        hlogo: '/clublogos/Kristiansund.png',
        homegoal: '1',
        clubscorer: 'Haugesund',
        scorer: "Ibrahima Wadji",
        alogo: '/clublogos/Haugesund.png',
        awaygoal: '3',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/as10uqa7czeof",
    },
    {
        id: 2,
        videoimg:'/videopics/valerenga mal.jpg',
        hlogo: '/clublogos/Valerenga.png',
        homegoal: '4',
        clubscorer: 'vålerenga',
        scorer: "Aron Leonard Dønnum",
        alogo: '/clublogos/Rosenborg.png',
        awaygoal: '0',
        date : "7 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/anem5zoxapzi8",
    },
    {
        id: 3,
        videoimg:'/videopics/brann mal.jpg',
        hlogo: '/clublogos/Brann.png',
        homegoal: '2',
        clubscorer: 'Brann',
        scorer: "Jon-Helge ødegård Tveita",
        alogo: '/clublogos/Odd.png',
        awaygoal: '1',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/aazxf4271tpop",
    },
    {
        id: 4,
        videoimg:'/videopics/mjondalen mal.jpg',
        hlogo: '/clublogos/Mjondalen.png',
        homegoal: '3',
        clubscorer: 'Mjøndalen',
        scorer: "Markus Lund Nakkim",
        alogo: '/clublogos/Aalesund.png',
        awaygoal: '0',
        date : "22 Des 2020",
        videosource : "https://highlights.eliteserien.no/playlist/a9xdu0y9np1y",
    },
];

export default MostPopularData;