const TimelineData = [
    {
        id: 101,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '5',
        player : 'Kasper Aalund Junker',
        action : 'Skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/aue2e68tp1eup",
    },
    {
        id: 102,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '14',
        player : 'Sondre Brunstad Fet',
        action : 'mål',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/akozsc4p6z2e7",
    },
    {
        id: 103,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '18',
        player : 'Philip Aksel Frigast Zinckernagel',
        action : 'Skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/anem24xdg7v1j",
    },
    {
        id: 104,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '20',
        player : 'Ola Selvaag Solbakken',
        action : 'Skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/agxn27zzh1a7w",
    },
 {
        id: 105,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '21',
        player : 'Ulrik Saltnes',
        action : 'Skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a1bzzvf4ghnh4",
    },   
    {
        id: 106,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '21',
        player : 'Kasper Aalund Junker',
        action : 'mål',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/aj63bep4dvrpd",
    },
    {
        id: 107,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '28',
        player : 'Ulrik Saltnes',
        action : 'Skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a7rlotsapyvf8",
    },
    {
        id: 108,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '29',
        player : 'Kasper Aalund Junker',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a4z4c8su4s3va",
    },
    {
        id: 109,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '37',
        player : 'Patrick Berg',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/amycmo2pks9uh",
    },
    {
        id: 110,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '40',
        player : 'Philip Aksel Frigast Zinckernagel',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/ahqxserqiew91",
    },
    {
        id: 111,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '44',
        player : 'kasper Aalund Junker',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/af2kvwhli0nus",
    },
    {
        id: 112,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '45',
        player : 'Ulrik Saltnes',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/ah6pp5aqzkkpa",
    },
    {
        id: 113,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '46',
        player : 'Ulrik Saltnes',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/ac360jy88j8pk",
    },
    {
        id: 114,
        position : 'away',
        team : 'Viking',
        clublogo : '/clublogos/Viking.png',
        time : '47',
        player : 'Ylldren Ibrahimaj',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/am8qbizwxd55p",
    },
    {
        id: 115,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '48',
        player : 'Sondre Brunstad Fet',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/afyo9447gu2xi",
    },
    {
        id: 116,
        position : 'away',
        team : 'Viking',
        clublogo : '/clublogos/Viking.png',
        time : '64',
        player : 'Joe Zen Robert Bell',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/aa5dttw1yws8q",
    },
    {
        id: 117,
        position : 'away',
        team : 'Viking',
        clublogo : '/clublogos/Viking.png',
        time : '64',
        player : 'Fredik Torsteinbø',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/aa5dttw1yws8q",
    },
    {
        id: 118,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '72',
        player : 'Patrick Berg',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/auemvet6zr511",
    },
    {
        id: 119,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '80',
        player : 'Philip Aksel Frigast Zinckernagel',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a3jypdlpywz7k",
    },
    {
        id: 120,
        position : 'away',
        team : 'Viking',
        clublogo : '/clublogos/Viking.png',
        time : '81',
        player : 'Fredik Torsteinbø',
        action : 'mål',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a9rzm35e7b1r7",
    },
    {
        id: 121,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '82',
        player : 'Morten ågnes Konradsen',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/aqpqjla54b359",
        tab : "_self",
    },
    {
        id: 122,
        position : 'away',
        team : 'Viking',
        clublogo : '/clublogos/Viking.png',
        time : '87',
        player : 'viljar helland Vevatne',
        action : 'gult kort',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a2wvf0ti74xaq",
    },
    {
        id: 123,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '88',
        player : 'Patrick Berg',
        action : 'skudd',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a1o5t1l19tean",
    },
    {
        id: 124,
        position : 'home',
        team : 'Bodo/Glimt',
        clublogo : '/clublogos/BodoGlimt.png',
        time : '89',
        player : 'kasper Aalund Junker',
        action : 'mål',
        actionicon : '/actionicons/kick.png',
        videosource : "https://highlights.eliteserien.no/playlist/a9rzm35e7b1r7",
    },
];

export default TimelineData;